import type { NextPage } from "next";
import React, { useCallback, useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Table, IHeader } from "../components/Table/Table";
import store from "../store/store";
import { observer } from "mobx-react";
import Search from "../components/Search/Search";

const header: IHeader[] = [
  { displayName: "Name", key: "name" },
  { displayName: "Class", key: "class" },
  { displayName: "Birthday", key: "birthdate" },
  { displayName: "Gender", key: "gender" },
];

const ObservedStudentTable = observer(Table);

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Student Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
      <ObservedStudentTable header={header} body={store.filtered} />
    </div>
  );
};

export default Home;
