import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { studentData } from "./students";
import { useEffect, useState } from "react";
import Button from "../components/Button/Button";
import InputField from "../components/InputField/InputField";
import { Table, IHeader } from "../components/Table/Table";
import Selector from "../components/Selector/Selector";
const Home: NextPage = () => {
  // TODO : we probz don't need this
  const [students, setStudents] = useState(studentData);
  const [classes, setClasses] = useState<string[]>(["squok"]);
  // const ddlOptions = ["m", "f", "x"];

  const header: IHeader[] = [
    { displayName: "Name", key: "name" },
    { displayName: "Class", key: "class" },
    { displayName: "Birthday", key: "birthdate" },
    { displayName: "Gender", key: "gender" },
  ];

  // useEffect(() => {
  //   students.some((obj) => {
  //     Object.keys(obj).includes("class");
  //     if (!classes.includes(obj.class)) {
  //       console.log("FIX THIS", classes, obj.class);
  //       // setClasses((newClasses) => [...newClasses, obj.class]);
  //       setClasses(...classes, obj.class);
  //     }
  //   });
  // }, [students, classes]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Student Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Table header={header} body={students} />

      <Button variant="text" onClick={() => console.log("butt")}>
        Ayooo it a butt
      </Button>
      {/* <Selector options={ddlOptions} name="test" /> */}
      {/* <Selector options={classes} name="classes" /> */}
    </div>
  );
};

export default Home;
