import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import Button from "../components/Button/Button";
import { Table, IHeader } from "../components/Table/Table";
import store from "../store/store";
import { observer } from "mobx-react";

const Home: NextPage = () => {
  const ObservedStudentTable = observer(Table);

  const header: IHeader[] = [
    { displayName: "Name", key: "name" },
    { displayName: "Class", key: "class" },
    { displayName: "Birthday", key: "birthdate" },
    { displayName: "Gender", key: "gender" },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Student Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ObservedStudentTable header={header} body={store.students}>
        <Table header={header} body={store.students} />
      </ObservedStudentTable>

      <Button variant="text" onClick={() => console.log("butt")}>
        Ayooo it a butt
      </Button>
    </div>
  );
};

export default Home;
